version: '3.8'

services:
  postgres:
    image: postgres:14.18
    container_name: electronicvoting-db
    environment:
      POSTGRES_DB: vote
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vianney.237
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voting-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: electronicvoting-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/vote
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: vianney.237
      JWT_SECRET: your-secret-key-here
      EMAIL_USERNAME: fitj202@gmail.com
      EMAIL_PASSWORD: lmrh mqqq pjej tcbe
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - voting-network

volumes:
  postgres_data:

networks:
  voting-network:
    driver: bridge